version: "3.3"

services:
  back:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/copypaste

  cassandra:
    image: cassandra:3.11.10
    ports:
      - 9042:9042
    volumes:
      - cassandra-data:/var/lib/cassandra/data
    environment:
      - CASSANDRA_START_RPC=true


volumes:
  cassandra-data:
